<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="MUVI" duration-ms="72460" started-at="2021-06-10T13:41:22 IST" finished-at="2021-06-10T13:42:35 IST">
    <groups>
    </groups>
    <test name="Grouping" duration-ms="72460" started-at="2021-06-10T13:41:22 IST" finished-at="2021-06-10T13:42:35 IST">
      <class name="auto.qa.test.ContentTest">
        <test-method status="PASS" signature="fnBeforeSuite()[pri:0, instance:auto.qa.test.ContentTest@6a1aab78]" name="fnBeforeSuite" is-config="true" duration-ms="10209" started-at="2021-06-10T13:41:12 IST" finished-at="2021-06-10T13:41:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fnBeforeSuite -->
        <test-method status="PASS" signature="fnBeforeTest(java.lang.String, java.lang.reflect.Method)[pri:0, instance:auto.qa.test.ContentTest@6a1aab78]" name="fnBeforeTest" is-config="true" duration-ms="3816" started-at="2021-06-10T13:41:22 IST" finished-at="2021-06-10T13:41:26 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[public void auto.qa.test.ContentTest.validateContentTextTest() throws java.lang.Throwable]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fnBeforeTest -->
        <test-method status="FAIL" signature="validateContentTextTest()[pri:0, instance:auto.qa.test.ContentTest@6a1aab78]" name="validateContentTextTest" duration-ms="68468" started-at="2021-06-10T13:41:26 IST" finished-at="2021-06-10T13:42:35 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[waitForElementPresent : Falied to locate element Confirmation msg expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: waitForElementPresent : Falied to locate element Confirmation msg expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.automation.accelerators.ActionEngine.waitForElementPresent(ActionEngine.java:562)
at auto.qa.workflow.AddContenetPage.contentAddedConfirmationMsg(AddContenetPage.java:92)
at auto.qa.test.ContentTest.validateContentTextTest(ContentTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateContentTextTest -->
        <test-method status="PASS" signature="fnAfterTest()[pri:0, instance:auto.qa.test.ContentTest@6a1aab78]" name="fnAfterTest" is-config="true" duration-ms="110" started-at="2021-06-10T13:42:35 IST" finished-at="2021-06-10T13:42:35 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fnAfterTest -->
        <test-method status="PASS" signature="fnAfterSuite()[pri:0, instance:auto.qa.test.ContentTest@6a1aab78]" name="fnAfterSuite" is-config="true" duration-ms="1719" started-at="2021-06-10T13:42:35 IST" finished-at="2021-06-10T13:42:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fnAfterSuite -->
      </class> <!-- auto.qa.test.ContentTest -->
    </test> <!-- Grouping -->
  </suite> <!-- MUVI -->
</testng-results>
